#!/usr/bin/bash

for i in {1..10}; do
  curl -s -X POST http://localhost:8080/api/v1/task \
    -H "Content-Type: application/json" \
    -d "{
      \"name\": \"task $i\",
      \"description\": \"task $i really needs to be completed\",
      \"assigned_to\": \"dave\",
      \"status\": \"pending\",
      \"expires_at\": \"2025-09-13T09:50:00Z\"
    }" | jq &
done
wait

